image: ${JAVA_MAIN_IMAGE_NAME}:${JAVA_MAIN_IMAGE_TAG}

include:
  - project: 'singletonsd/pipelines/java'
    file: '/src/.gitlab-ci-main.yml'

variables:
  JAVA_MAIN_IMAGE_NAME: "maven"
  JAVA_MAIN_IMAGE_TAG: "3.5.2-jdk-8"
  JAVA_MAIN_EXECUTE_TEST: "true" # To execute test.
  JAVA_MAIN_EXECUTE_DEPLOY: "true" # To deploy to maven.
  ORIGINAL_REPOSITORY: "" # Put original repo name here to deploy.
stages:
  - build
  - test
  - deploy
  - package
